
# Note: this file's config override the Netlify UI admin config

# default/production build
[build]
  command = "yarn build"
  publish = "build"

[context.production]
  command = "yarn netlify:build:production"

# we build deploy previews with a /build/ baseUrl on purpose
# permits to test that baseUrl works fine (this often breaks!)
[context.deploy-preview]
  command = "yarn netlify:build:deployPreview"



[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache",
  ]
