
# Note: this file's config override the Netlify UI admin config

# default/production build
[build]
  base = "/"
  command = "yarn workspace docusaurus-2-website netlify:build:production"
  publish = "website/build"

# we build deploy previews with a /build/ baseUrl on purpose
# permits to test that baseUrl works fine (this often breaks!)
[context.deploy-preview]
  command = "yarn workspace docusaurus-2-website netlify:build:deployPreview"
  publish = "website/build"



[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    #"/opt/build/repo/website/node_modules/.cache",
    "MY_WEBPACK_CACHE",
  ]
