
# Note: this file's config overrides the Netlify UI admin config

[build]
  command = "yarn --cwd ... build && yarn build"
  publish = "build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "14"

[context.production]
  command = "yarn --cwd ... build && yarn netlify:build:production"

[context.deploy-preview]
  command = "yarn --cwd ... build && yarn netlify:build:deployPreview"


[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    # /!\ It seems path must be relative to monorepo root (not base dir or netlify.toml)
    # See https://github.com/netlify/build/issues/2483
    "node_modules/.cache/webpack",
  ]
